case class RSVPDetailsTest (
  rsvp_id : Long,
  event_name : String,
  event_time: Option[Long] ,
  event_url : String,
  group_city: String,
  group_country : String,
  group_id : Int,
  group_lat : Double,
  group_lon : Double,
  group_name : String,
  group_state : Option[String],
  group_topic_names: List[String],
  guests : Int,
  member_id : Long,
  member_name : String,
  response : String,
  mtime: Long,
  venue_id : Option[Int],
  venue_lat: Option[Double],
  venue_lon : Option[Double],
  venue_name: Option[String],
  visibility :String
                           )
